services:
  database:
    image: postgres:latest
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin1234
    ports:
      - '5432:5432'
volumes:
  database:
    driver: local
