services:
  database:
    image: postgres:latest
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin1234
    ports:
      - '5432:5432'

  keycloak:
    image: jboss/keycloak
    environment:
      - KEYCLOAK_USER=quarkus
      - KEYCLOAK_PASSWORD=quarkus123
    ports:
      - '8888:8080'
volumes:
  database:
    driver: local
